name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  port: ${{ secrets.WING_SSH_PORT }}
                  host: ${{ secrets.WING_SSH_HOST }}
                  username: ${{ secrets.WING_SSH_USER }}
                  key: ${{ secrets.WING_SSH_KEY }}
                  script: |
                      cd ${{ secrets.SERVER_DEPLOY_DIR }}
                      git pull origin main
