image: buildpack-deps:jessie-scm

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y lftp
    - mkdir -p .ssh && chmod 700 .ssh
    - echo "${WING_SSH_KEY}" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
    - lftp -e "set net:max-retries 1; set sftp:connect-program \"ssh -a -x -p ${WING_SSH_PORT} -i .ssh/id_rsa -o StrictHostKeyChecking=no\"; connect sftp://${WING_SSH_USER}:@${WING_SSH_HOST}; mirror -eR -x .git -x .ssh ./ ${SERVER_DEPLOY_DIR}; quit"
